import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LinkComponent from "@/components/LinkComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex antialiased min-h-screen min-w-screen justify-center`}
      >
        <main className="flex flex-col justify-center items-center text-white gap-4">
          <div>{children}</div>
          <LinkComponent className="bg-blue-400 text-white font-bold px-2 py-1 rounded-lg" href="/">Voltar</LinkComponent>
        </main>

      </body>
    </html>
  );
}
