import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LinkComponent from "@/components/LinkComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gradient-to-b from-neutral-900 via-neutral-800 to-neutral-900 flex antialiased h-screen w-screen justify-center`}
      >
        <main className="flex flex-col justify-center items-center text-white gap-4">
          <div>{children}</div>
          <LinkComponent className="bg-gray-500 text-sm text-white font-bold px-4 py-2 rounded-sm" href="/">Voltar</LinkComponent>
        </main>

      </body>
    </html>
  );
}
